// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Generates product titles using AI to reduce manual writing effort.
 *
 * - generateProductTitle - A function that generates a product title based on a product description.
 * - GenerateProductTitleInput - The input type for the generateProductTitle function.
 * - GenerateProductTitleOutput - The return type for the generateProductTitle function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateProductTitleInputSchema = z.object({
  productDescription: z
    .string()
    .describe('The description of the product for which to generate a title.'),
});
export type GenerateProductTitleInput = z.infer<typeof GenerateProductTitleInputSchema>;

const GenerateProductTitleOutputSchema = z.object({
  productTitle: z.string().describe('The generated title for the product.'),
});
export type GenerateProductTitleOutput = z.infer<typeof GenerateProductTitleOutputSchema>;

export async function generateProductTitle(input: GenerateProductTitleInput): Promise<GenerateProductTitleOutput> {
  return generateProductTitleFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateProductTitlePrompt',
  input: {schema: GenerateProductTitleInputSchema},
  output: {schema: GenerateProductTitleOutputSchema},
  prompt: `You are an expert in generating creative and catchy product titles.

  Based on the product description provided, generate a title that is both informative and appealing to customers.

  Product Description: {{{productDescription}}}`,
});

const generateProductTitleFlow = ai.defineFlow(
  {
    name: 'generateProductTitleFlow',
    inputSchema: GenerateProductTitleInputSchema,
    outputSchema: GenerateProductTitleOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
